services:
  - type: web
    name: manarah
    env: node
    buildCommand: npm run build && npm run install:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
